# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print(np.__version__)

1.21.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [35]:
# Method 1
a=np.random.random((2,3,5))

In [31]:
# Method 2
a=np.random.rand(2,3,5)

In [33]:
# Method 3
a=np.random.randint(10,size=(2,3,5))

#### 4. Print *a*.


In [36]:
# your code here
print(a)

[[[0.85017623 0.3731368  0.39960116 0.0706281  0.50429387]
  [0.36229855 0.88115837 0.80810941 0.6638575  0.76142405]
  [0.17841414 0.94171954 0.93966291 0.30525342 0.41652762]]

 [[0.86574762 0.17020992 0.63789566 0.89952933 0.77752806]
  [0.88773427 0.00242065 0.38081739 0.11381754 0.13467622]
  [0.12084708 0.32235768 0.85268023 0.28224438 0.58323174]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# your answer here: no, because they do not have the same shape
ab=np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [12]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
c=np.transpose(b,(1, 2, 0))
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
d=np.add(a,c)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here
print(d)

[[[1.61882127 1.66635394 1.47304135 1.17874457 1.31051501]
  [1.18077376 1.32991319 1.88556391 1.8997786  1.67430327]
  [1.78920593 1.06131667 1.76455228 1.81613385 1.72614332]]

 [[1.66883604 1.89610126 1.74037399 1.51424141 1.30471911]
  [1.98544889 1.35178646 1.00014223 1.74976581 1.18925709]
  [1.96361515 1.46856148 1.72729221 1.56057042 1.17706202]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [16]:
# your code here
e=np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?


In [17]:
# your code/answer here
print(e)

[[[6.18821266e-01 6.66353940e-01 4.73041351e-01 1.78744566e-01
   3.10515011e-01]
  [1.80773763e-01 3.29913192e-01 8.85563907e-01 8.99778598e-01
   6.74303269e-01]
  [7.89205926e-01 6.13166680e-02 7.64552283e-01 8.16133849e-01
   7.26143316e-01]]

 [[6.68836036e-01 8.96101263e-01 7.40373986e-01 5.14241406e-01
   3.04719112e-01]
  [9.85448891e-01 3.51786464e-01 1.42225088e-04 7.49765815e-01
   1.89257092e-01]
  [9.63615152e-01 4.68561481e-01 7.27292211e-01 5.60570421e-01
   1.77062025e-01]]]


In [18]:
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [19]:
#Yes, because a==a*I (a matrix multiplied by the identity matrix return the same value)

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [20]:
# your code here
d_max=np.max(d)
print(d_max)
d_min=np.min(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.9854488905730525
1.0001422250882612
1.5557644827343964


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
# your code here
f=np.empty(shape=[2,3,5])
print(f)

[[[6.18821266e-01 6.66353940e-01 4.73041351e-01 1.78744566e-01
   3.10515011e-01]
  [1.80773763e-01 3.29913192e-01 8.85563907e-01 8.99778598e-01
   6.74303269e-01]
  [7.89205926e-01 6.13166680e-02 7.64552283e-01 8.16133849e-01
   7.26143316e-01]]

 [[6.68836036e-01 8.96101263e-01 7.40373986e-01 5.14241406e-01
   3.04719112e-01]
  [9.85448891e-01 3.51786464e-01 1.42225088e-04 7.49765815e-01
   1.89257092e-01]
  [9.63615152e-01 4.68561481e-01 7.27292211e-01 5.60570421e-01
   1.77062025e-01]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [44]:
f= [25 if z>d_min and z<d_mean else 75 if z>d_mean 
 and z<d_max else 50 if z==d_mean else 0 if  z==d_min else 100 for x in d for y in x for z in y]

In [45]:
f=np.reshape(f, (2,3,5))

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [53]:
print(d)

[[[1.61882127 1.66635394 1.47304135 1.17874457 1.31051501]
  [1.18077376 1.32991319 1.88556391 1.8997786  1.67430327]
  [1.78920593 1.06131667 1.76455228 1.81613385 1.72614332]]

 [[1.66883604 1.89610126 1.74037399 1.51424141 1.30471911]
  [1.98544889 1.35178646 1.00014223 1.74976581 1.18925709]
  [1.96361515 1.46856148 1.72729221 1.56057042 1.17706202]]]


In [46]:
print(f)

[[[ 75  75  25  25  25]
  [ 25  25  75  75  75]
  [ 75  25  75  75  75]]

 [[ 75  75  75  25  25]
  [100  25   0  75  25]
  [ 75  25  75  75  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
f= ["B" if z>d_min and z<d_mean else "D" if z>d_mean 
 and z<d_max else "C" if z==d_mean else "A" if  z==d_min else "E" for x in d for y in x for z in y]

In [51]:
f=np.reshape(f,(2,3,5))

In [52]:
print(f)

[[['D' 'D' 'B' 'B' 'B']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']]

 [['D' 'D' 'D' 'B' 'B']
  ['E' 'B' 'A' 'D' 'B']
  ['D' 'B' 'D' 'D' 'B']]]
